// <auto-generated />
using System;
using ASSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASSystem.Migrations
{
    [DbContext(typeof(AccommodationSearchSystemContext))]
    [Migration("20240310192005_databaseUpdate")]
    partial class databaseUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ASSystem.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"), 1L, 1);

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("date")
                        .HasColumnName("deleteAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AccountId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Username", "Phone", "Email" }, "IX_Account")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL AND [Phone] IS NOT NULL");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("ASSystem.Models.Convenient", b =>
                {
                    b.Property<int>("ConvenientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConvenientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConvenientId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ConvenientId");

                    b.ToTable("Convenient", (string)null);
                });

            modelBuilder.Entity("ASSystem.Models.Motel", b =>
                {
                    b.Property<int>("MotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MotelID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotelId"), 1L, 1);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Contact")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteAt");

                    b.Property<string>("Description")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("District")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Province")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("QuantityEmptyRooms")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tittle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ward")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MotelId");

                    b.ToTable("Motel", (string)null);
                });

            modelBuilder.Entity("ASSystem.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentId");

                    b.HasIndex("AccountId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("ASSystem.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("ASSystem.Models.RoomImage", b =>
                {
                    b.Property<int>("RoomImageId")
                        .HasColumnType("int")
                        .HasColumnName("RoomImageID");

                    b.Property<string>("ImageDetail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("imageDetail");

                    b.Property<int>("MotelId")
                        .HasColumnType("int")
                        .HasColumnName("MotelID");

                    b.Property<string>("PathImageDetail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pathImageDetail");

                    b.HasKey("RoomImageId");

                    b.HasIndex("MotelId");

                    b.ToTable("RoomImage", (string)null);
                });

            modelBuilder.Entity("ASSystem.Models.Vote", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<int>("MotelId")
                        .HasColumnType("int")
                        .HasColumnName("MotelID");

                    b.Property<string>("ReviewStar")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.HasKey("AccountId", "MotelId");

                    b.HasIndex("MotelId");

                    b.ToTable("Vote", (string)null);
                });

            modelBuilder.Entity("Facility", b =>
                {
                    b.Property<int>("MotelId")
                        .HasColumnType("int")
                        .HasColumnName("MotelID");

                    b.Property<int>("Covenient")
                        .HasColumnType("int");

                    b.HasKey("MotelId", "Covenient")
                        .HasName("PK_Facility_1");

                    b.HasIndex("Covenient");

                    b.ToTable("Facility", (string)null);
                });

            modelBuilder.Entity("ASSystem.Models.Account", b =>
                {
                    b.HasOne("ASSystem.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Account_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ASSystem.Models.Payment", b =>
                {
                    b.HasOne("ASSystem.Models.Account", "Account")
                        .WithMany("Payments")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_Payment_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ASSystem.Models.RoomImage", b =>
                {
                    b.HasOne("ASSystem.Models.Motel", "Motel")
                        .WithMany("RoomImages")
                        .HasForeignKey("MotelId")
                        .IsRequired()
                        .HasConstraintName("FK_RoomImage_Motel");

                    b.Navigation("Motel");
                });

            modelBuilder.Entity("ASSystem.Models.Vote", b =>
                {
                    b.HasOne("ASSystem.Models.Account", "Account")
                        .WithMany("Votes")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_Vote_Account");

                    b.HasOne("ASSystem.Models.Motel", "Motel")
                        .WithMany("Votes")
                        .HasForeignKey("MotelId")
                        .IsRequired()
                        .HasConstraintName("FK_Vote_Motel");

                    b.Navigation("Account");

                    b.Navigation("Motel");
                });

            modelBuilder.Entity("Facility", b =>
                {
                    b.HasOne("ASSystem.Models.Convenient", null)
                        .WithMany()
                        .HasForeignKey("Covenient")
                        .IsRequired()
                        .HasConstraintName("FK_Facility_Convenient");

                    b.HasOne("ASSystem.Models.Motel", null)
                        .WithMany()
                        .HasForeignKey("MotelId")
                        .IsRequired()
                        .HasConstraintName("FK_Facility_Motel");
                });

            modelBuilder.Entity("ASSystem.Models.Account", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ASSystem.Models.Motel", b =>
                {
                    b.Navigation("RoomImages");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ASSystem.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
